### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by nas5w** [nas5w/use-local-storage#1]
Add `CODE_OF_CONDUCT.md` file.

Recommend using the "Contributor Covenant" template unless there's a good reason to use something else.

**Comment by comradekingu** [comment]
Is there reason to add any?

**Comment by nas5w** [comment]
Yes, it is generally recommended for projects at initiation https://opensource.guide/starting-a-project/

**Comment by comradekingu** [comment]
@nsd5w GitHub seems to think so, yes. It was at GitHub the CoC they advertise was written, by a person trying to foster communication between upstream and newcomers. That same person was fired for not doing so later.
I am unaware that it has any greater merit to its name, but I could be wrong.

It seems to me the part that says "every project should" is smuggling an ought into the equation.

The textfile in question has since been rewritten multiple times, yet the recommendation is there. Have you read it, and if so what do you think about the changes from 1.4 to 2.0?

Just curious.
